In [1]:
import numpy as np


In [2]:
my_list = [10,20,30,40]

In [3]:
type(my_list)

list

In [4]:
np.array(my_list)

array([10, 20, 30, 40])

In [5]:
my_numpy_array = np.array(my_list)

In [6]:
my_numpy_array

array([10, 20, 30, 40])

In [7]:
type(my_numpy_array)

numpy.ndarray

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
np.random.random(5)

array([0.19420564, 0.25805377, 0.3076665 , 0.22112151, 0.52939887])