In [5]:
import numpy as np


In [6]:
my_list = [10,20,30,40]

In [7]:
type(my_list)

list

In [8]:
np.array(my_list)

array([10, 20, 30, 40])

In [9]:
my_numpy_array = np.array(my_list)

In [10]:
my_numpy_array

array([10, 20, 30, 40])

In [11]:
type(my_numpy_array)

numpy.ndarray

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
np.random.random(5)

array([0.45067326, 0.79247634, 0.60142637, 0.46970779, 0.51563071])

In [15]:
my_list1 = [1,2]

In [16]:
my_list2 = [2,3]

In [17]:
my_list1 + my_list2

[1, 2, 2, 3]

In [18]:
my_numpy_array1 = np.array(my_list1)

In [19]:
my_numpy_array2 = np.array(my_list2)

In [20]:
my_numpy_array1 + my_numpy_array2

array([3, 5])

In [21]:
my_numpy_array1 * 5

array([ 5, 10])

In [22]:
num = [10,20,50,80]

In [23]:
num[0]

10

In [24]:
num[-1]

80

In [25]:
num[-2]

50

In [26]:
num[1:]

[20, 50, 80]

In [29]:
num[1::2]

[20, 80]

In [32]:
num1 = (10,20,30,50,400)

#Bu bir aggregation ornegiydi. 

In [36]:
a = np.array([10,20,50,80])

In [37]:
total = np.sum(a)

In [39]:
print(total)

160


In [40]:
total = np.min(a)

In [41]:
print(total)

10


In [42]:
total = np.max(a)
print(total)

80


In [44]:
emre = ([100,200,300,400,500])

total = np.sum(emre)
print(total)

1500


In [45]:
#indexing & arange

In [46]:
#indexing & arange

In [47]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [48]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [52]:

np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [53]:
np_array = np.arange(0,10)

In [54]:
np_array[0]

0

In [56]:
np_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
np_array[2:6:2]

array([2, 4])

In [58]:
# random


In [59]:
np.random.randn(4)

array([-0.75637494,  2.3396014 , -1.17899338, -0.48903677])

In [60]:
np.random.randn(4,4)

array([[-1.66026952,  0.88382744, -0.0027204 ,  0.50394594],
       [-0.70742414, -0.16061817,  0.52099688, -0.69489232],
       [-0.91884521, -0.3267114 , -1.18481347,  0.52489547],
       [-0.23621959,  0.59225618,  0.30222313,  1.79326727]])

In [64]:
np.random.randint(1,300,5) #bir ile 300 arasinda bana 5 tane sayi ver. int dedigi icin tam sayi vericek. 

array([124,  80,  37, 176, 201])