In [1]:
import numpy as np 

In [2]:
my_matrix = [[5,10], [15,20]]

In [4]:
my_matrix[0]

[5, 10]

In [5]:
my_matrix[1]

[15, 20]

In [6]:
# row * colum  = sira * kolon

In [7]:
numpy_matrix = np.array([[5,10],[15,20]])

In [12]:
numpy_matrix

array([[ 5, 10],
       [15, 20]])

In [13]:
numpy_matrix[0] [1]

10

In [14]:
numpy_matrix[1] [0]

15

In [15]:
numpy_matrix.sum()

50

In [16]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [17]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:

np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [20]:
np.random.random((3,2))

array([[0.12092611, 0.96659308],
       [0.69236499, 0.19614129],
       [0.92962066, 0.85488004]])

In [21]:
# matrix arithmetic

In [24]:
first_array = np.array([[10,20], [30,40]])

In [25]:
second_array = np.array([[5,15], [25,35]])

In [26]:
first_array + second_array

array([[15, 35],
       [55, 75]])

In [27]:

first_array * 2

array([[20, 40],
       [60, 80]])

In [29]:
first_array / 4

array([[ 2.5,  5. ],
       [ 7.5, 10. ]])

In [28]:
# We can add and multiply matrices using arithmetic operators (+-*/) if the two matrices are the same size.

In [30]:
third_array = np.array([[10],[20]])

In [31]:
third_array.shape

(2, 1)

In [32]:
first_array.shape

(2, 2)

In [33]:
first_array + third_array

array([[20, 30],
       [50, 60]])

In [34]:
# We do these arithmetic operations on matrices of different size only if the different dimension is one 
#in which case NumPy uses its broadcast rules for that operation:

In [35]:
fourth_array = np.ones((3,4))

In [36]:
fourth_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [37]:
# matrix multiplication

In [38]:
first_matrix = np.array ([[10,20,30]])

In [39]:
first_matrix

array([[10, 20, 30]])

In [40]:
second_matrix = np.array([[2,3],[2,3],[2,3]])

In [41]:
second_matrix

array([[2, 3],
       [2, 3],
       [2, 3]])

In [42]:
first_matrix.shape

(1, 3)

In [43]:
second_matrix.shape

(3, 2)

In [44]:
#first_matrix * second_matrix

In [47]:

result_matrix = first_matrix.dot(second_matrix)

In [48]:
result_matrix

array([[120, 180]])

In [49]:
result_matrix.shape

(1, 2)