In [1]:
import numpy as np

In [3]:
new_array = np.random.randint(1,100,20)

In [4]:
new_array

array([21, 92, 11, 77, 55, 43, 43, 47, 95, 91, 97, 50, 51, 51, 52, 54, 23,
       14,  3, 50])

In [5]:
new_array > 25

array([False,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
       False,  True])

In [6]:
new_array [new_array < 25]

array([21, 11, 23, 14,  3])

In [7]:
new_array [new_array > 25]

array([92, 77, 55, 43, 43, 47, 95, 91, 97, 50, 51, 51, 52, 54, 50])

In [8]:
#transpose & reshape

In [9]:
matrix_array = np.array ([[10,20],[20,30],[30,40]])

In [10]:
matrix_array

array([[10, 20],
       [20, 30],
       [30, 40]])

In [11]:
matrix_array.shape

(3, 2)

In [12]:
matrix_array.transpose()

array([[10, 20, 30],
       [20, 30, 40]])

In [13]:
matrix_array.T

array([[10, 20, 30],
       [20, 30, 40]])

In [14]:
random_array = np.random.random((6,1))

In [15]:
random_array

array([[0.51561442],
       [0.85374353],
       [0.7482157 ],
       [0.67875222],
       [0.84607723],
       [0.73563646]])

In [16]:
random_array.reshape(2,3)

array([[0.51561442, 0.85374353, 0.7482157 ],
       [0.67875222, 0.84607723, 0.73563646]])

In [17]:
#z-score

In [18]:
data = np.array([10,12,13,15,18,25,100,105])

In [19]:
#outlier

In [20]:
mean = np.mean(data)

In [21]:
mean


37.25

In [22]:
data.sum() / len(data)

37.25

In [23]:
std = np.std(data)

In [25]:
std

37.9333296719389